import { describe, it, expect, beforeAll, afterAll } from "vitest"
import { prisma } from "./prisma"
import { listParticipants, createParticipant } from "./participant-repo"

const hasDb = Boolean(process.env.DATABASE_URL)

describe.skipIf(!hasDb)("listParticipants (integration)", () => {
  let createdId: number

  beforeAll(async () => {
    const p = await prisma.participant.create({
      data: {
        firstName: "Repo",
        lastName: "Test",
        dob: new Date("1990-01-01"),
        sex: "male",
        weightValue: "150",
        weightUnit: "lb",
        heightValue: "70",
        heightUnit: "in",
        bmi: "21.5",
      },
      select: { id: true },
    })
    createdId = p.id
  })

  afterAll(async () => {
    await prisma.participant.delete({ where: { id: createdId } })
    await prisma.$disconnect()
  })

  it("maps generated columns to numbers in the DTO and leaks no PII", async () => {
    const { data, total } = await listParticipants({ page: 1, pageSize: 100 })
    expect(total).toBeGreaterThan(0)
    const row = data.find((r) => r.id === createdId)!
    expect(typeof row.weightKg).toBe("number")
    expect(row.weightKg).toBeCloseTo(68.0389, 3) // 150 lb -> kg, generated by Postgres
    expect(row.weightLb).toBeCloseTo(150, 3) // entered as lb, stored verbatim
    expect(row.heightCm).toBeCloseTo(177.8, 2) // 70 in -> cm
    expect(row.heightIn).toBeCloseTo(70, 2) // entered as in, stored verbatim
    expect(row.dob).toBe("1990-01-01")
    expect(row).not.toHaveProperty("phone")
    expect(row).not.toHaveProperty("email")
  })
})

describe.skipIf(!hasDb)("createParticipant (integration)", () => {
  const ids: number[] = []

  afterAll(async () => {
    for (const id of ids) await prisma.participant.delete({ where: { id } })
    await prisma.$disconnect()
  })

  it("inserts a participant without a contact and returns the mapped record", async () => {
    const rec = await createParticipant({
      firstName: "Grace", lastName: "Hopper", dob: "1980-05-05", sex: "female",
      weightValue: 60, weightUnit: "kg", heightValue: 165, heightUnit: "cm", bmi: 22.0,
    })
    ids.push(rec.id)
    expect(rec.weightKg).toBeCloseTo(60, 3)
    expect(rec.heightCm).toBeCloseTo(165, 2)
    expect(rec.bmi).toBe(22)
    const contact = await prisma.contact.findUnique({ where: { participantId: rec.id } })
    expect(contact).toBeNull()
  })

  it("inserts a nested contact when provided", async () => {
    const rec = await createParticipant({
      firstName: "Alan", lastName: "Turing", dob: "1975-06-23", sex: "male",
      weightValue: 154, weightUnit: "lb", heightValue: 70, heightUnit: "in", bmi: 22.1,
      contact: { phone: "555-0100", email: "alan@example.com" },
    })
    ids.push(rec.id)
    const contact = await prisma.contact.findUnique({ where: { participantId: rec.id } })
    expect(contact?.email).toBe("alan@example.com")
  })
})
