import { describe, it, expect, beforeAll, afterAll } from "vitest"
import { prisma } from "./prisma"
import { listParticipants } from "./participant-repo"

const hasDb = Boolean(process.env.DATABASE_URL)

describe.skipIf(!hasDb)("listParticipants (integration)", () => {
  let createdId: number

  beforeAll(async () => {
    const p = await prisma.participant.create({
      data: {
        firstName: "Repo",
        lastName: "Test",
        dob: new Date("1990-01-01"),
        sex: "male",
        weightValue: "150",
        weightUnit: "lb",
        heightValue: "70",
        heightUnit: "in",
        bmi: "21.5",
      },
      select: { id: true },
    })
    createdId = p.id
  })

  afterAll(async () => {
    await prisma.participant.delete({ where: { id: createdId } })
    await prisma.$disconnect()
  })

  it("maps generated columns to numbers in the DTO and leaks no PII", async () => {
    const { data, total } = await listParticipants({ page: 1, pageSize: 100 })
    expect(total).toBeGreaterThan(0)
    const row = data.find((r) => r.id === createdId)!
    expect(typeof row.weightKg).toBe("number")
    expect(row.weightKg).toBeCloseTo(68.0389, 3) // 150 lb -> kg, generated by Postgres
    expect(row.weightLb).toBeCloseTo(150, 3) // entered as lb, stored verbatim
    expect(row.heightCm).toBeCloseTo(177.8, 2) // 70 in -> cm
    expect(row.heightIn).toBeCloseTo(70, 2) // entered as in, stored verbatim
    expect(row.dob).toBe("1990-01-01")
    expect(row).not.toHaveProperty("phone")
    expect(row).not.toHaveProperty("email")
  })
})
