import { describe, it, expect, beforeAll, afterAll } from "vitest"
import { execFileSync } from "node:child_process"
import {
  PostgreSqlContainer,
  type StartedPostgreSqlContainer,
} from "@testcontainers/postgresql"

// These suites boot their OWN throwaway Postgres via Testcontainers. The
// connection string is generated at runtime and points at a container that did
// not exist a moment ago, so this test can never touch a real/production
// database — it never reads .env. The whole DB is discarded on afterAll, so no
// per-row cleanup is needed. Run with `npm run test:integration` (requires
// Docker); the default `npm test` excludes *.integration.test.ts.
//
// ./prisma reads DATABASE_URL at import time, so we set it to the container URL
// first and import the repo/client dynamically once the container is up.

let container: StartedPostgreSqlContainer
let prisma: typeof import("./prisma").prisma
let listParticipants: typeof import("./participant-repo").listParticipants
let createParticipant: typeof import("./participant-repo").createParticipant

beforeAll(async () => {
  container = await new PostgreSqlContainer("postgres:17").start()
  process.env.DATABASE_URL = container.getConnectionUri()

  // Apply the real migrations so the generated columns exist exactly as in
  // production (prisma.config.ts reads DATABASE_URL from the environment).
  execFileSync("npx", ["prisma", "migrate", "deploy"], {
    env: process.env,
    stdio: "inherit",
  })

  ;({ prisma } = await import("./prisma"))
  ;({ listParticipants, createParticipant } = await import("./participant-repo"))
}, 180_000) // first run pulls the postgres:17 image, which can be slow

afterAll(async () => {
  await prisma?.$disconnect()
  await container?.stop()
})

describe("listParticipants (integration)", () => {
  let createdId: number

  beforeAll(async () => {
    const p = await prisma.participant.create({
      data: {
        firstName: "Repo",
        lastName: "Test",
        dob: new Date("1990-01-01"),
        sex: "male",
        weightValue: "150",
        weightUnit: "lb",
        heightValue: "70",
        heightUnit: "in",
        bmi: "21.5",
      },
      select: { id: true },
    })
    createdId = p.id
  })

  it("maps generated columns to numbers in the DTO and leaks no PII", async () => {
    const { data, total } = await listParticipants({
      page: 1,
      pageSize: 100,
      sort: "createdAt",
      order: "desc",
    })
    expect(total).toBeGreaterThan(0)
    const row = data.find((r) => r.id === createdId)!
    expect(typeof row.weightKg).toBe("number")
    expect(row.weightKg).toBeCloseTo(68.0389, 3) // 150 lb -> kg, generated by Postgres
    expect(row.weightLb).toBeCloseTo(150, 3) // entered as lb, stored verbatim
    expect(row.heightCm).toBeCloseTo(177.8, 2) // 70 in -> cm
    expect(row.heightIn).toBeCloseTo(70, 2) // entered as in, stored verbatim
    expect(row.dob).toBe("1990-01-01")
    expect(row).not.toHaveProperty("phone")
    expect(row).not.toHaveProperty("email")
  })

  it("orders by the generated full_name column, case-insensitively", async () => {
    const marker = "Zzcasemark"
    const base = {
      lastName: marker,
      dob: new Date("1990-01-01"),
      sex: "male" as const,
      weightValue: "150",
      weightUnit: "lb" as const,
      heightValue: "70",
      heightUnit: "in" as const,
      bmi: "21.5",
    }
    // createdAt runs opposite to name order, so a createdAt/id sort would return
    // ["Banana", "apple"] — only a case-insensitive full_name sort yields ["apple", "Banana"].
    await Promise.all([
      prisma.participant.create({
        data: { ...base, firstName: "apple", createdAt: new Date("2020-01-02T00:00:00Z") },
        select: { id: true },
      }),
      prisma.participant.create({
        data: { ...base, firstName: "Banana", createdAt: new Date("2020-01-01T00:00:00Z") },
        select: { id: true },
      }),
    ])
    const { data } = await listParticipants({
      page: 1,
      pageSize: 100,
      sort: "fullName",
      order: "asc",
    })
    const names = data.filter((r) => r.lastName === marker).map((r) => r.firstName)
    expect(names).toEqual(["apple", "Banana"])
  })
})

describe("createParticipant (integration)", () => {
  it("inserts a participant without a contact and returns the mapped record", async () => {
    const rec = await createParticipant({
      firstName: "Grace", lastName: "Hopper", dob: new Date("1980-05-05"), sex: "female",
      weightValue: 60, weightUnit: "kg", heightValue: 165, heightUnit: "cm", bmi: 22.0,
    })
    expect(rec.weightKg).toBeCloseTo(60, 3)
    expect(rec.heightCm).toBeCloseTo(165, 2)
    expect(rec.bmi).toBe(22)
    const contact = await prisma.contact.findUnique({ where: { participantId: rec.id } })
    expect(contact).toBeNull()
  })

  it("inserts a nested contact when provided", async () => {
    const rec = await createParticipant({
      firstName: "Alan", lastName: "Turing", dob: new Date("1975-06-23"), sex: "male",
      weightValue: 154, weightUnit: "lb", heightValue: 70, heightUnit: "in", bmi: 22.1,
      contact: { create: { phone: "555-0100", email: "alan@example.com" } },
    })
    const contact = await prisma.contact.findUnique({ where: { participantId: rec.id } })
    expect(contact?.email).toBe("alan@example.com")
  })
})
